# Shell variables
# Generated by 'wal'
wallpaper='/home/crochi/Dropbox/wallpapers/jsVtkXq.jpg'

# Special
background='#120f0c'
foreground='#dee0e2'
cursor='#dee0e2'

# Colors
color0='#120f0c'
color1='#7E807E'
color2='#8A847B'
color3='#949492'
color4='#A1A19D'
color5='#ACAFAF'
color6='#BDC0C2'
color7='#dee0e2'
color8='#EFF5F9'
color9='#7E807E'
color10='#8A847B'
color11='#949492'
color12='#A1A19D'
color13='#ACAFAF'
color14='#BDC0C2'
color15='#dee0e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
