# Shell variables
# Generated by 'wal'
wallpaper='/home/crochi/Dropbox/wallpapers/anime1.jpg'

# Special
background='#0c0304'
foreground='#e7d2ba'
cursor='#e7d2ba'

# Colors
color0='#0c0304'
color1='#768665'
color2='#B5895E'
color3='#BB8A69'
color4='#D58E42'
color5='#CD996D'
color6='#B29E85'
color7='#e7d2ba'
color8='#E3CE99'
color9='#768665'
color10='#B5895E'
color11='#BB8A69'
color12='#D58E42'
color13='#CD996D'
color14='#B29E85'
color15='#e7d2ba'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
