# Shell variables
# Generated by 'wal'
wallpaper='/home/crochi/Pictures/wallhaven-wood1.jpg'

# Special
background='#fcfbf9'
foreground='#242020'
cursor='#242020'

# Colors
color0='#fcfbf9'
color1='#668b99'
color2='#997666'
color3='#997966'
color4='#997c66'
color5='#668d99'
color6='#668f99'
color7='#242020'
color8='#7e7d7c'
color9='#668b99'
color10='#997666'
color11='#997966'
color12='#997c66'
color13='#668d99'
color14='#668f99'
color15='#242020'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
